#### Description of estimatiors/model : 
* **Homogeneous Model** : This model assumes that all species have the same discovery probabilities. See Eq.(2.3) of Lee and Chao (1992) or Eq. (2.1) of Chao et al. (2000).  

* **Homogeneous (MLE)** : An approximate maximum likelihood estimate under homogeneous model. See Eq.(1.1) and Eq. (1.2) of Lee and Chao (1992).  
    
* **Chao1 (Chao, 1984)** : This approach uses the numbers of singletons and doubletons to estimate the number of missing species because missing species information is mostly concentrated on those low frequency counts; see Chao (1984), Shen, Chao and Lin (2003) and Chao, Shen and Hwang(2006).
  
* **Chao1-bc** : a bias-corrected form for the Chao1: see Chao (2005).

* **iChao1** : a improved form for the Chao1: see Chiu (2013). (to appear)

* **ACE (Abundance-based Coverage Estimator)** : A non-parametric estimator proposed by Chao and Lee (1992) and Chao, Ma and Yang (1993). The observed species are separated as rare and abundant groups; only the rare group is used to estimate the nubmer of missing species. The estimated CV is used to characterize the degree of heterogeneity among species discovery probabilities. See Eq. (2.14) in Chao and Lee (1992) or Eq. (2.2) of Chao et al. (2000).


* **ACE-1** : A modified ACE for highly-heterogeneous communities. See Eq. (2.15) in Chao and Lee (1992).

* **1st order jackknife** : It uses the number of singletons and doubletons to estimate the number of missing species; see Burnham and Overton (1978).

* **2nd order jackknife** : It uses the number of singletons and doubletons to estimate the number of missing species; see Burnham and Overton (1978).